url: "http://example.com"
poll_interval: 5 # in seconds
certainty_level: 5 # num times a change needs to be seen to alert
alerting:
  smtp:
    host: "smtp.gmail.com"
    username: "username" # your email as username for stmp
    password: "password"
    emails:
      - "example1@gmail.com"
      - "example2@gmail.com"
  sms: # sms not supported yet
    account_id: "ugh"
    auth_token: "agh"
    numbers: 
      - "8881234567"